### PR TITLE
Introduced LUA 5.1 support without breaking 5.2 or 5.3.

### PR DESCRIPTION
**Pull request by KingJaTu**
By design, LUA is meant to be embedded into software. This results in situation, where there is virtually zero possibility of me upgrading LUA version. However, I'd like to add some features into my LUA, including LevelDB support. This patch adds the 5.1 build, while still working with newer versions too.

### CODE REVIEW

**Comment by marcopompili** [comment]
Hey, thank you for the pull reqs, I'll check them out ASAP, everything seems very interesting but I'd rather avoid keeping Lua 5.1, this fragmentation between 5.1/5.2/5.3 is ruining Lua IMO, I'll merge what i can.

**Comment by KingJaTu** [comment]
The critical part here is: _virtually zero possibility of me upgrading LUA version_

**This library has two major flaws:**
1. A lot of LUA users don't get to choose their LUA version. They just use what is there in the app they want to extend. My use case is exactly like that, I don't build my app, I just use it.
1. By design LevelDB is key-value -storage storing only binary arrays. This LUA library *must* implement exactly that. However, in its current form only LUA internal representations are stored, making it unusable for interconnectivity. My use case is to store data to be read and processed later with Python and Ruby.

So, please, try to direct this project into generally usable direction instead of making it suit only your needs. I hate to see the typical open-source thing happen, that there are two developers developing the same thing without actually collaborating.

**Comment by marcopompili** [comment]
1. Fair enough, what are you using btw? just curious.
2. I'll restore both options, it was plain binary before, I added Lua internals because in my case I use only Lua instances.

Right now the source is very different from github, will take me a little.

**Comment by KingJaTu** [comment]
I'm running [Openresty](https://openresty.org/en/).

And I appreciate you taking these suggestions seriously. In the end, it will help more people than just us. And for the record, I'm running my own unpublished build now just to avoid the two-libraries -situation.

**Pull request merged**
